### ISSUE TITLE
opengroup() fails with wrong exception

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/code#182]
**Original reporter**: *Cpascual*

The documentation says that opengroup() should raise ValueError if it fails to open the group.
Instead it fails with:

```
<type 'exceptions.TypeError'>: not all arguments converted during string formatting
```

in __getnxclass()

I think this is a bug in `__getnxclass()` and it affects other API functions as well (e.g. openpath)

**Comment by eugenwintersberger** [comment]
This issue has been moved to https://github.com/nexusformat/python-nxs/issues/5. Please continue discussion there.
