### ISSUE TITLE
effects of missing dependencies are hidden

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/code#240]
**Original reporter**: *[zjttoefs](https://github.com/zjttoefs)*

There is no obvious way to tell that xml2 is required to build nxsummary and nxtranslate. If you just run configure even when you make sure everything in the report is correct and compile you just don't get those two programs. If you just look what new stuff has been installed you may not even be aware they existed (I wasn't really).

It would be useful to report that in the configuration report at the end of configure as well.

There is at least an opengenie dependency with the same behaviour.

**Comment by zjttoefs** [comment]
To be decided with new cmake build.

**Comment by eugenwintersberger** [comment]
This is indeed a problem. What I would have to do is to check the dependencies for each package which should be built (including the napi library itself). I have not done this yet but will put it on my todo list. What makes the entire thing a bit complicated is that all dependencies are listed in the main CMakeLists.txt and I have no idea for which program a particular dependency is required. Maybe I need to look into the autotools configuration to learn more about this ;)
