### ISSUE TITLE
make external links to datasets work in C++, Python and Fortran

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/code#274]
**Original reporter**: *[zjttoefs](https://github.com/zjttoefs)*

The current NAPI only supports links to groups. We suspect a main use case for linking to an external file is writing data into two files from an acquisition system and directly from a detector (for obvious performance reasons) but having them as a single logical unit for data analysis by the user. This use case has two main problems with linking to groups:
 - The detector needs to write the entire NXdetector group and hence has to know the entire metadata you might want there. With the level of control you have over detector file writing that is a major drawback.
 - It is not possible to link the detector data into an /entry/nxdata from /entry/instrument/detector/data as that needs to cross file boundaries (correct me if I'm wrong there).
If it was possible to link to an SDS, these limitations would not exist.

**Comment by zjttoefs** [comment]
Broken out into individual tickets, especially since python has moved out from here.
