### ISSUE TITLE
Major revision to tree.py

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/code#322]
**Original reporter**: *[rayosborn](https://github.com/rayosborn)*

As I discussed on the NeXus mailing list a few weeks ago, there has been a major rewrite of the tree API that makes the API more robust and more convenient to use interactively. The major changes are:

1) to give the NXfields (formerly SDSs) all the functionality of Numpy arrays

2) to allow group items to be accessed through a dictionary interface

3) to make the syntax cleaner by simplifying method names. 

I will be uploading a new version shortly, which will not be backwardly compatible with the previous one. Please contact Ray Osborn <ROsborn@anl.gov> if you need assistance upgrading to the new version.

**Comment by eugenwintersberger** [comment]
This issue has been moved to https://github.com/nexusformat/python-nxs/issues/6. Please continue commenting there.
