### ISSUE TITLE
nxvalidate and nxconvert crash on Windows 7

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/code#326]
**Original reporter**: *[FreddieAkeroyd](https://github.com/FreddieAkeroyd)*

Hi,

I am trying to run the above tools through MinGW on Window 7 but they fail run with the following messages:

nxvalidate stopped working
Problem signature:
  Problem Event Name: APPCRASH
  Application Name: nxvalidate.exe
  Application Version: 0.0.0.0
  Application Timestamp: 49ee00df
  Fault Module Name: msvcrt.dll
  Fault Module Version: 7.0.7600.16385
  Fault Module Timestamp: 4a5bda6f
  Exception Code: c0000005
  Exception Offset: 00009c7f
  OS Version: 6.1.7601.2.1.0.256.48
  Locale ID: 2057
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\windows\system32\en-US\erofflps.txt

Any advice?

Regards
Arif

-*****************************************************************
Dr Arif Shaon

Senior Software Research Scientist,
Scientific Information Group,
E-Science Centre, Science and Technology Facilities Council,
Rutherford Appleton Laboratory Chilton, Didcot, OX11 0QX, UK
tel: +44 1235 778178
arif.shaon@stfc.ac.uk<mailto:arif.shaon@stfc.ac.uk>
-- 
Scanned by iCritical.

_______________________________________________
NeXus-committee mailing list
NeXus-committee@nexusformat.org
http://lists.nexusformat.org/mailman/listinfo/nexus-committee

**Comment by eugenwintersberger** [comment]
`nxvalidate` is no longer an issue as it will be rewritten anyhow by Mark.
