### ISSUE TITLE
Windows install kit with CMake

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/code#330]
**Original reporter**: *[zjttoefs](https://github.com/zjttoefs)*

Also document procedure. README.cmake is currently empty.

Was requested in http://trac.nexusformat.org/definitions/ticket/242

**Comment by zjttoefs** [comment]
To be looked at in connection with the cmake build.

**Comment by eugenwintersberger** [comment]
Just for curiosity: how was the dependency stuff done on Windows until now? Static linking or installation of all dependencies along with the programs (something like C:\Programs\nexus\bin)?

**Comment by FreddieAkeroyd** [comment]
All DLLs and exe go into the same "bin" directory, but this "bin" directory is also added to PATH by the installer and similarly the "lib" directory (for static and import libraries) is added to the LIB environment variable

**Comment by eugenwintersberger** [comment]
Ok. This is good to know.
