### ISSUE TITLE
remove limitation for attributes to be single value only and allow arrays

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/code#356]
**Original reporter**: *[zjttoefs](https://github.com/zjttoefs)*

Mainly for transformations and their vectors http://download.nexusformat.org/doc/html/design.html?highlight=vector but useful in general.

**Comment by benajamin** [comment]
This bug is blocking implementation of the new method of assigning dimentions to data arrays by writing attributes at the group level that was voted for at the December 2014 NIAC.

**Comment by zjttoefs** [comment]
This should be fixed in master actually. We'd just need to make a release with that in now, I believe.

**Comment by benajamin** [comment]
Is there a timeline for when this release would be made?

**Comment by zjttoefs** [comment]
Question for Eugen now, I guess. I would hope soon.

On 12 Jan 2015 18:14, Ben Watts <notifications@github.com> wrote:

Is there a timeline for when this release would be made?

**Comment by zjttoefs** [comment]
I still believe this is fixed in master. Closing
