### ISSUE TITLE
how to validate data files?

### ISSUE THREAD

**Issue by prjemian** [nexusformat/code#363]
Build a working data file validation tool.  
The tool must be able to read valid HDF5 files which are not NeXus-compliant.
Tool should run on any platform.
This tool must be kept current.
Tool must run from either command-line without GUI or in a GUI.

Expected outcome from 2014 Code Camp

**Comment by eugenwintersberger** [comment]
As discussed during the Telecon on January 10, 2016 this issue can be closed as the functionality is provided by cnxvalidate (https://github.com/nexusformat/cnxvalidate).
