### ISSUE TITLE
content on downloads page is stale

### ISSUE THREAD

**Issue by prjemian** [nexusformat/code#367]
regarding: http://download.nexusformat.org/

Various links and other information on this page are now stale.  Such as:
* page title: "NeXus Data Format Development Home" should be something such as "NAPI downloads"
* NeXus code bug/feature request system (points to TRAC)
* Notes for NeXus Subversion developers (use GitHub now)
* URLs to documentation generated by doxygen get **404 Not Found** errors (https://github.com/nexusformat/definitions/issues/414)
* NXDL Tutorial (now part of manual)
 * new location: http://download.nexusformat.org/doc/html/applying-nexus.html
* links to NeXus manual, should only link to HTML now
 * PDF is not built at this time, https://github.com/nexusformat/definitions/issues/406

**Comment by FreddieAkeroyd** [comment]
Does that look better? The doxygen is not currently generated from git, that's the next job

**Comment by prjemian** [comment]
That's great, thanks!
