### ISSUE TITLE
NXconvert libraries

### ISSUE THREAD

**Issue by eugenwintersberger** [nexusformat/code#372]
Parts of `nxconvert` are built as static and shared libraries and later linked to the final program. Is there any reason why this is the case? Are there applications out there which are using this library?

If this is not the case we should remove the libraries and just install the binary along with its man-page.

**Comment by eugenwintersberger** [comment]
According to Pete Peterson (the original author of nxconvert) the libraries can be removed.

**Comment by FreddieAkeroyd** [comment]
The library was broken off for use in validation  (HDF -> XML). When validation went to java, the nxconvert executable was spawned directly so I expect a separate library is no longer needed.
