### ISSUE TITLE
nxdir license

### ISSUE THREAD

**Issue by eugenwintersberger** [nexusformat/code#374]
The `nxdir` license seems to be something somehow strange. It is definitely not GPL. Maybe some MIT license. However, we should relicense this under the GPL.

Are there any obstacles with this?

**Comment by rayosborn** [comment]
Do we use GPL elsewhere? That can be dangerous if we are to allow, for example, detector manufacturers to incorporate the API into their software.

Ray

On Nov 5, 2015, at 6:36 AM, Eugen Wintersberger <notifications@github.com<mailto:notifications@github.com>> wrote:


The nxdir license seems to be something somehow strange. It is definitely not GPL. Maybe some MIT license. However, we should relicense this under the GPL.

Are there any obstacles with this?

—
Reply to this email directly or view it on GitHub<https://github.com/nexusformat/code/issues/374>.

--
Ray Osborn, Senior Scientist
Materials Science Division
Argonne National Laboratory
Argonne, IL 60439, USA
Phone: +1 (630) 252-9011
Email: ROsborn@anl.gov<mailto:ROsborn@anl.gov>

**Comment by yayahjb** [comment]
Dear Colleagues,
  When working with commercial vendors and using the GPL, it is important
to also allow the LGPL for anything they might choose to incorporate into
one of their proprietary applications, and these days _any_ application may
end up being incorporated in another application as if it was an API, so I
would suggest using both the GPL and the LGPL for everything.
  Regards,
    Herbert

**Comment by eugenwintersberger** [comment]
Hi folks
  I agree with both of you. Currently it seems to be a mixture of
different licenses including GPL and some custom ones. Indeed, not all
source files have a license header and therefore cannot be considered as
licensed at all.

I guess that dual licensing using GPL (strictly version 2) and LGPL is a
good idea.

I would suggest that after we have a stable build and decided which
features go into the final product I will review all the files and check
their licenses. This will be a bit of work but I think it is worth to do
it.

regards
  Eugen

PS: do not forget: run the build, run the test, and submit issues if
something goes wrong ;)

**Comment by eugenwintersberger** [comment]
According to Pete the software is distributed under the MIT license. As this license is compatible with the GPL and LGPL there should be no problems. I will close this ticket for now. However, we may want to have a review of all licenses somewhere in the future. Just to ensure that all code is distributed under the same license.
