### ISSUE TITLE
NXclass::buff2str (in applications/nxingest/nxingest_nexus.cpp)

### ISSUE THREAD

**Issue by chrisemblhh** [nexusformat/code#377]
I'm not sure whether the programs in 'applications' are just supposed to be examples or whether they are supposed to be production quality. If the latter, then there are several problems with this function.

* It writes a string to the `value` buffer without knowing the size of the buffer.
* It overwrites the `vector` input argument (and unnecessarily, because `atoi` ignores non-numeric characters after the end of the number). More generally, it doesn't use `const` to mark input arguments.
* It uses the wrong format strings for `sprintf`
* It assumes that e.g. `NX_UINT32` is the same as `unsigned int`

**Comment by chrisemblhh** [comment]
Also, nxingest writes "neXus" with a small 'n' - I thought the canonical capitalisation was "NeXus".

**Comment by eugenwintersberger** [comment]
Hi Chris. Just one important comment in advance: please work on the cmake_build branch. We will switch to cmake soon and it would not make too much sense to continue working on the current master.

Back to your questions:

* the programs in `applications` are intended for productive use
* I currently only reviewed the build system, not the application code itself. Thus it is very likely that some of the code is buggy. 

I will have a look on your points a bit later. If you find more issues in the code do not hesitate to open more tickets ;)

**Comment by eugenwintersberger** [comment]
Do you have time to do this?

**Comment by chrisemblhh** [comment]
I have created a fixed `buff2str`. Fixing the wider problems in NXingest will take more thought though...
