### ISSUE TITLE
Install F77 .inc file and possibly F90 .mod files

### ISSUE THREAD

**Issue by chrisemblhh** [nexusformat/code#387]
To use the F77 API the napif.inc file is needed, to use the F90 API the nxmodule.mod and/or nxumodule.mod files must be available.

In the case of .mod files, they are only valid for the same compiler version, so perhaps the .f90 files should be installed as well / instead.

**Comment by eugenwintersberger** [comment]
The include file for Fortran 77 is installed. As there is no reasonable way of how to install the .mod files for Fortran90 this part of the issue will not be fixed.
