### ISSUE TITLE
Cmake misses tests

### ISSUE THREAD

**Issue by PeterC-DLS** [nexusformat/code#397]
Looking at the generated Makefile from cmake in the test directory, I see it is missing tests specified in the Makefile.am

**Comment by eugenwintersberger** [comment]
Can you be more precise which tests are missing ;). Cmake is not missing tests, it is more likely that I have not implemented them.

**Comment by PeterC-DLS** [comment]
I've add the attribute array tests in my fork [https://github.com/PeterC-DLS/code/commit/a5ba1d96db869447ffe3f00659c075fcc505c72e]. Unfortunately I didn't create a new branch so am waiting till my previous pull request [https://github.com/nexusformat/code/pull/396] succeeds.

**Comment by eugenwintersberger** [comment]
Ok

**Comment by eugenwintersberger** [comment]
This should be fixe with the last commit.
