### ISSUE TITLE
CMake packages are missing symbols

### ISSUE THREAD

**Issue by peterfpeterson** [nexusformat/code#399]
When using the [python bindings](https://github.com/nexusformat/python-nxs) with the new cmake builds, there is a missing symbol.
```
$ NEXUSLIB=/usr/lib64/libNeXus.so python
Python 2.7.10 (default, Sep  8 2015, 17:20:17) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nxs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nxs/__init__.py", line 20, in <module>
    from nxs.napi import *
  File "nxs/napi.py", line 266, in <module>
    nxlib = _init()
  File "nxs/napi.py", line 261, in _init
    lib = _libnexus()
  File "nxs/napi.py", line 257, in _libnexus
    "NeXus library %s could not be loaded: %s"%(file,sys.exc_info())
OSError: NeXus library /usr/lib64/libNeXus.so could not be loaded: (<type 'exceptions.OSError'>, OSError('/usr/lib64/libNeXus.so: undefined symbol: DFdiput',), <traceback object at 0x7ff9ee436f38>)
```
This is doesn't happen with v4.3.

**Comment by eugenwintersberger** [comment]
Hi Pete
What Linux distribution are you running on your system? I read Red Hat 5.1.1 with GCC 5.1.1 - sounds strange to me ;)

**Comment by eugenwintersberger** [comment]
Hi Pete
What Linux distribution are you running on your system? I read Red Hat 5.1.1 with GCC 5.1.1 - sounds strange to me ;)

**Comment by peterfpeterson** [comment]
fedora 23

**Comment by eugenwintersberger** [comment]
Thanks for the info.

**Comment by eugenwintersberger** [comment]
Hm. The problem I have here is that I cannot reproduce it on my Debian box. With NEXUSLIB set to the library the `import nxs` works fine for me here.

**Comment by eugenwintersberger** [comment]
Have you installed the HDF4 libraries from Fedoras package repository or from sources in a custom location. In the latter case this might be a linker issue.

**Comment by peterfpeterson** [comment]
They are from fc23 packages (read: rpm), but it isn't entirely clear where I got them from.

**Comment by eugenwintersberger** [comment]
Ok. We are one step closer to a solution. I could reproduce the bug on a Fedora 23 system and will do some more investigation tomorrow.

**Comment by eugenwintersberger** [comment]
Fixed. The problem was static linking of the HDF4 libraries.

**Comment by eugenwintersberger** [comment]
@FreddieAkeroyd please check the current master on Windows again. I think we have to do some more stuff for mxml.

**Comment by FreddieAkeroyd** [comment]
@eugenwintersberger just pushed some changes #408 to fix mxml and also some static/shared linking conflicts
