### ISSUE TITLE
nxtranslate HDF4 build error

### ISSUE THREAD

**Issue by FreddieAkeroyd** [nexusformat/code#400]
Building 4.4.0 with

cmake .. -DENABLE_APPS=BOOLEAN:TRUE -DENABLE_MXML=BOOLEAN:TRUE -DENABLE_HDF4=BOOLEAN:TRUE

give link error for NXtranslate 

Linking CXX executable nxtranslate
/usr/lib64/hdf/libmfhdf.a(cdf.o): In function `hdf_write_var':
(.text+0xb29): undefined reference to `DFdisetup'
/usr/lib64/hdf/libmfhdf.a(cdf.o): In function `hdf_write_var':
(.text+0xb5a): undefined reference to `DFdiput'
/usr/lib64/hdf/libmfhdf.a(cdf.o): In function `hdf_write_var':
(.text+0xb7d): undefined reference to `DFdiput'

looks like linking of df library for HDF4 is either missing or in the wrong order, may be related to #399 ?

**Comment by eugenwintersberger** [comment]
Fixed with Freddies latest pull request.
