### ISSUE TITLE
CMake build system does not work on Windows

### ISSUE THREAD

**Issue by FreddieAkeroyd** [nexusformat/code#404]
Errors such as:

CMake Error at src/CMakeLists.txt:96 (install):
  install Library TARGETS given no DESTINATION!

**Comment by eugenwintersberger** [comment]
I do not wonder that the build on Windows does not work. If I recall correctly this particular error has something to do with the missing `ARCHIVE` option in the `install` command.

**Comment by FreddieAkeroyd** [comment]
Thanks - In this case it was "GNUInstallDirs" not being called on windows, but I may come across the issue you mention at a later point so will keep it in mind

**Comment by eugenwintersberger** [comment]
I think it would make sense to move the development for windows to a new branch. Can you open a ``Windows`` branch for this purpose?
