### ISSUE TITLE
Include files do not all go into the same directory

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/code#405]
Some of the C/C++ header files are written to the system include dir (e.g. `/usr/include/`) and some to a `nexus` subdirectory.  We just need to decide on one place.

**Comment by eugenwintersberger** [comment]
You are totally right. I would suggest to put everything below `$PREFIX/include/nexus`.

**Comment by stuartcampbell** [comment]
Also, are there any header files we should be shipping that we currently don't ? e.g. `napi_internal.h` etc..
