### ISSUE TITLE
MXML unit tests failing on windows

### ISSUE THREAD

**Issue by FreddieAkeroyd** [nexusformat/code#410]
Crashes in NXXflush() -> mxmlSaveFile()

**Comment by eugenwintersberger** [comment]
@FreddieAkeroyd thanks for assigning this issue to yourself ;) I would not have known how to help. Is this a problem related to my last commit?

**Comment by FreddieAkeroyd** [comment]
@eugenwintersberger no it isn't, I've only just noticed it wasn't working. But actually it is now working if I run ctest from visual studio, but not if I run from the command line. Sound familiar :-D

**Comment by eugenwintersberger** [comment]
Surprisingly enough I have now running tests on all testing systems. I had to delete the build directory. Most probably something from a previous configuration remained persistent and messed up the build.

**Comment by eugenwintersberger** [comment]
@FreddieAkeroyd will you fix this one today? This would be our last issue for the 4.4.1 release. So it would be nice if I can do this today.

**Comment by FreddieAkeroyd** [comment]
@eugenwintersberger Not sure, the way my day is looking at the moment i'll not be able to start looking at it properly until about 1630 GMT I'm afraid...

**Comment by FreddieAkeroyd** [comment]
I think this is actually OK and was caused by my mxml and nexus DLL's being linked against different C run time libraries. The save requires a FILE* pointer to be passed, which is not safe to do across RTL boundaries.
