### ISSUE TITLE
Add CPack install kit building

### ISSUE THREAD

**Issue by FreddieAkeroyd** [nexusformat/code#412]

**Comment by eugenwintersberger** [comment]
@FreddieAkeroyd Just for your information. I learned yesterday that as of version 3.0.2 or so CPack also provides a WiX generator. I will give this a try during my christmas holidays.

**Comment by FreddieAkeroyd** [comment]
@eugenwintersberger  that sounds good, the NSIS interface is a bit of a pain sometimes, especially with environment variables.

**Comment by eugenwintersberger** [comment]
Can we close this issue with your last pull request?

**Comment by FreddieAkeroyd** [comment]
yes, I think it's good for now
