### ISSUE TITLE
Missing symbols in version 4.4

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/code#414]
I have noticed a number of symbols are missing from the latest release.  This is not an exhaustive list, just the ones I noticed when trying to compile mantid using it.
```
NXMSetError
NXMEnableErrorReporting
NXsetcache
```

There are also a number of deprecated functions, such as `NXgetnextattr` - is this intentional ?

**Comment by stuartcampbell** [comment]
@eugenwintersberger Any joy looking into this ?

**Comment by zjttoefs** [comment]
The only thing I can contribute is the depreciation of  `NXgetnextattr`. 
`NXgetnextattr` cannot deal with attribute arrays, which are now part of the standard. For those to work you need  `NXgetnextattra` which also works for the standard simple case.

I didn't introduce the deprecation, but can see the intention behind it.

No idea why the symbols are missing.

**Comment by eugenwintersberger** [comment]
The only symbols I am missing on my Debian build  is NXsetcache. 
@stuartcampbell did you make any progress on this? On which platform you are building?

**Comment by stuartcampbell** [comment]
To be honest I was waiting for you! :smile: 
I have been mainly testing on RHEL/Fedora systems... I will try and build a kit on ubuntu to see what's missing..

**Comment by eugenwintersberger** [comment]
Sorry for being late on this. I was pretty occupied with other work ;). Ok. Then go ahead with Ubuntu and let me know what you are missing.

**Comment by FreddieAkeroyd** [comment]
Did those functions get moved into an internal api in #391 ?

**Comment by stuartcampbell** [comment]
Looks like it did - was this a deliberate design decision ?

**Comment by zjttoefs** [comment]
Not a design decision. Backward compatibility still is the primary goal.

**Comment by eugenwintersberger** [comment]
@stuartcampbell can you provide a list of all symbols that are missing? Is this an error you get during linking?

**Comment by stuartcampbell** [comment]
@eugenwintersberger for what I am doing (compiling mantid) the list is at the top of this issue.  And yes, it appears as compilation/linking issues.

**Comment by eugenwintersberger** [comment]
@stuartcampbell Can you send me the cmake configuration you used to build the NeXus library?
The only symbol I am missing in my build is NXsetcache, though I have no idea yet why it is not exported.

**Comment by zjttoefs** [comment]
Can we not just move the functions that are clearly not internal back into the main napi.h?
Commit d547d59fdae69101d40b838d7159271c94e3ec0f had to import napi_internal.h in our own example tools in order to compile. So it was clear then those were not private internals.

**Comment by chrisemblhh** [comment]
Missing symbols (which show up as link errors rather than compile errors) don't depend on the header files but rather on whether the functions are declared as static / extern / __attribute__((hidden)) etc.

On moving functions to napi_internal.h I just went on which functions were declared as 'internal' in the comments in napi.h. If those comments were correct then the example code should not have been using the internal functions. Alternatively the comments were wrong and those functions should be part of the public API.

**Comment by eugenwintersberger** [comment]
I guess we should discuss this issue again during todays hangout.

**Comment by stuartcampbell** [comment]
Any updates ?

**Comment by eugenwintersberger** [comment]
Ok guys. I am totally lost with this. I have no idea why the symbols are not in Stuarts build. Moving the function declarations to `napi_internal.h` could not be the reason (see the post of Chris above). 
Also the fact that they are declared as `extern` could not cause this effect as these functions were declared external in the `napi.h` too. Most probably the reason is something totally simple which I just failed to see.

Any ideas?

**Comment by zjttoefs** [comment]
I think the reason people now have to include napi_internal.h in their code in order for it to compile is reason enough to revert that change in any case, though. I'm not quite seeing how Stu got it to do that without edits in the first place. Maybe I'm missing something.

In case that wasn't clear enough though: Those are NOT internal functions. None of them.

Keeping the struct in the _internal would be okay, I guess. Once we've got the functions back, we can see if we still have a problem.

**Comment by eugenwintersberger** [comment]
Ok. I've moved the functions back to napi.h. 
@stuartcampbell can you try to build with the code from the issue_414 branch?

**Comment by stuartcampbell** [comment]
@eugenwintersberger Thank you - will do

**Comment by stuartcampbell** [comment]
It looks good to me, stuff that didn't work with 4.4.1 now works! :smile:

**Comment by eugenwintersberger** [comment]
Ok so I will close this issue.
