### ISSUE TITLE
support new method of signal/axes

### ISSUE THREAD

**Issue by prjemian** [nexusformat/code#416]
In https://github.com/nexusformat/definitions/pull/439#issuecomment-174515822, it was asserted that the "nexusformat API cannot read the new axis_indices".  This is related to https://github.com/nexusformat/definitions/issues/434.

The NeXus API should support the new method for identifying the default data to be plotted.

**Comment by zjttoefs** [comment]
There used to be a test case for attribute arrays as required for axis_indices since summer 2014. So I'm not convinced that is actually a true assertion.
Or is there another problem?

**Comment by rayosborn** [comment]
I meant the Python API in that comment. The C-API doesn't have high-level functions for identifying NXdata axes. Sorry I wasn't more specific.

**Comment by zjttoefs** [comment]
Okay, that was my first reading, but I could have misinterpreted that. Closing here.
