### ISSUE TITLE
CMake doesn't install all NXtranslate libraries

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/code#419]
When building and subsequently installing `NXtranslate` the current CMake config files do not actually install the required libraries.

**Comment by eugenwintersberger** [comment]
I guess these libraries should not be in the default installation. So I suggest to add a switch in the configuration in order to install the libraries. Are there any header files which should be installed?

**Comment by eugenwintersberger** [comment]
@stuartcampbell Hi Stuart. Can you please check if the current branch issue-419 fits your requirements?
