### ISSUE TITLE
Add support for HDF5 1.10

### ISSUE THREAD

**Issue by peterfpeterson** [nexusformat/code#421]
This doesn't affect a ton of systems (yet), but HDF5 v1.10 changed the function signatures in much of the API. According to their [compatibility document](https://www.hdfgroup.org/HDF5/doc/RM/APICompatMacros.html), NeXus just needs to add `-DH5_USE_18_API` to its compilation.

**Comment by zjttoefs** [comment]
Discussed at Telco. We'll give it some priority.

**Comment by eugenwintersberger** [comment]
Though the code compiles now all tests fail. It seems there is some more work to do rather than just setting the H5_USE_18_API preprocessor directive.

**Comment by mkoennecke** [comment]
I fixed this so far that it stands its own self test. Which further testing is required?

**Comment by mkoennecke** [comment]
I merged issue-421 with master as discussed in the Telco. With this we close this ticket for the time being.
