### ISSUE TITLE
nxinter is not built

### ISSUE THREAD

**Issue by mkoennecke** [nexusformat/code#425]
For some locally used tools I need to have the Tcl swig bindings built. It has yet to be decided if this 
makes it into the master. But I create an issue and a branch for it in the repository in order to keep 
the necessary changes to the cmake files end else.

**Comment by eugenwintersberger** [comment]
Can be built optionally.

**Comment by eugenwintersberger** [comment]
@mkoennecke The SWIG-TCL build is currently in the branch issue_425. Where should we install this stuff?

**Comment by mkoennecke** [comment]
Hi Eugen,


Am 19.05.2016 um 15:57 schrieb Eugen Wintersberger <notifications@github.com<mailto:notifications@github.com>>:


@mkoennecke<https://github.com/mkoennecke> The SWIG-TCL build is currently in the branch issue_425. Where should we install this stuff?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/nexusformat/code/issues/425#issuecomment-220332062>

if we are willing to adopt this at all, the the shared library has to end up in the usual library directory where the NeXus libraries
live. This is the place where I put them on installing.

Regards,

    Mark

**Comment by eugenwintersberger** [comment]
Is there anything else that should be installed? Btw. there is a header file 'nxdataset.h' missing in the source directory of the TCL binding. Any idea where this is gone?

**Comment by mkoennecke** [comment]
Eugen,


Am 19.05.2016 um 16:42 schrieb Eugen Wintersberger <notifications@github.com<mailto:notifications@github.com>>:


Is there anything else that should be installed? Btw. there is a header file 'nxdataset.h' missing in the source directory of the TCL binding. Any idea where this is gone?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/nexusformat/code/issues/425#issuecomment-220345476>

That header is in in the src directory of the NAPI. Nxdataset is used in the construction of the XML-API. My latest version of issue-425
has the include paths properly adjusted for it to be found by the swig binding.

Regards,

    Mark

**Comment by eugenwintersberger** [comment]
Stupid me - I missed your issue branch ;)

**Comment by eugenwintersberger** [comment]
@mkoennecke Hi Mark. I have added now the installation of libnxinter and nxinter. 
Can you please check if branch issue-425 fits your needs?

**Comment by mkoennecke** [comment]
Eugen,


Am 30.05.2016 um 10:01 schrieb Eugen Wintersberger <notifications@github.com<mailto:notifications@github.com>>:


@mkoennecke<https://github.com/mkoennecke> Hi Mark. I have added now the installation of libnxinter and nxinter.
Can you please check if branch issue-425 fits your needs?


Issue-425 fits the bill. Nxinter is optionally being built.

Regards,

    Mark

**Comment by eugenwintersberger** [comment]
Fixed.
