### ISSUE TITLE
make check fails on OS X 10.11

### ISSUE THREAD

**Issue by quantumsteve** [nexusformat/code#427]
The python tests are failing when I try installing NeXus 4.3.3 via Homebrew on OS X 10.11 (El Capitan). The same install script works fine on OS X 10.10 and below. Another issue with more information is [here](https://github.com/Homebrew/homebrew-science/issues/3593).

I believe the problem is that system integrity protection [strips `DYLD_LIBRARY_PATH` from the environment variables](http://apple.stackexchange.com/questions/215030/el-capitan-make-check-dyld-library-path). I can work around this issue by adding `NEXUSLIB=@abs_top_builddir/src/.libs/.libs/libNeXus.0.dylib` in the ['TESTS_ENVIRONMENT variable](https://github.com/nexusformat/code/blob/353b0750b081042e7b8c12bc20da00acc76f4e32/test/Makefile.am#L121), but I fear that may not be a portable solution.

**Comment by zjttoefs** [comment]
Thanks Steve,

The new build system (4.4 onward) uses cmake, so the fix would have to be different or at least in a different place.

**Comment by quantumsteve** [comment]
This issue goes away in master because the python bindings have been moved to a separate repository. Homebrew installs `libNeXus.0.dylib` in `/usr/local` where it can be found by the python tests. 

When do you plan to release the next version with the changes from issue #414?

**Comment by zjttoefs** [comment]
Steve,
Then I guess we can close this here. I'll add the release to the agenda for our telco on Tuesday. There are a couple of C++ problems to be fixed before a release, I would say. One of them raised by yourself. Other than that we could push out an update relatively quick, because not much has gone in, I believe.
