### ISSUE TITLE
Bump version number to 4.4.2 before release

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/code#432]
Just a reminder issue to bump the version number before the 4.4.2 release.  @eugenwintersberger , I presumed that you would be doing it, so assigned this to you! :smile:

**Comment by stuartcampbell** [comment]
So this wasn't  done then? :(

**Comment by eugenwintersberger** [comment]
Actually I changed the package version to 4.4.2 in the CMakeLists.txt. Have you found any other place where this should be changed?

**Comment by stuartcampbell** [comment]
https://github.com/nexusformat/code/blob/v4.4.2/include/napi.h

**Comment by eugenwintersberger** [comment]
I see. Thanks for the hint. Do we have any other locations in the code where the version number is hard-coded? I definitely need to change this.
