### ISSUE TITLE
tag v4.4.3 reporting API_VERSION=4.4.2

### ISSUE THREAD

**Issue by quantumsteve** [nexusformat/code#437]
The `API_VERSION` variable which determines the value of the `NEXUS_VERSION` macro in `napi.h` has the wrong patch version. 

https://github.com/nexusformat/code/blob/v4.4.3/CMakeLists.txt#L72

`NEXUS_VERSION_PATCH` has the same issue and should also be updated.

https://github.com/nexusformat/code/blob/v4.4.3/CMakeLists.txt#L81

**Comment by eugenwintersberger** [comment]
Scheduled for tomorrow.

**Comment by stuartcampbell** [comment]
@eugenwintersberger - would it be worth moving the 'release tag' to now point to https://github.com/nexusformat/code/commit/75d3592f7491912ab1a52822904872ccc4d79126
