### ISSUE TITLE
NXgetnextattr is deprecated without a replacement

### ISSUE THREAD

**Issue by peterfpeterson** [nexusformat/code#438]
v4.4 has deprecated `NXgetnextattr` which is currently the only way to generate a list of attribute names. If `NXgetnextattr` is removed, then there is no way to loop through all attributes on a group/data. Instead client code will have to guess all possible attributes and see if they exist by checking the return codes on `NXgetattr`. It looks like you could use (in HDF5) [`H5Aget_name`](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5A.html#Annot-GetName) to expose the names of the attributes for iteration.

**Comment by zjttoefs** [comment]
What about NXgetnextattra?


________________________________

**Comment by peterfpeterson** [comment]
That works. It would be great if the deprecation message (from the compiler) suggested `NXgetnextattra`.
