### ISSUE TITLE
How to build NAPI with non-default locations for HDF5 and SZIP?

### ISSUE THREAD

**Issue by prjemian** [nexusformat/code#444]
@MarkRivers asks how to specify non-default locations for HDF5 and SZIP when building the NAPI.  A minimal configuration that worked was obtained by running

    cmake -i

but this uses the system defaults for HDF5 and SZIP.

Also, how to build for 32 bits?

**Comment by FreddieAkeroyd** [comment]
I think you can set the HDF5_ROOT environment variable as a hint to cmake

**Comment by MarkRivers** [comment]
I have a number of questions:

- Where can I find the release notes for Nexus?  The nexusformat/code/NEWS file only seems to have notes up to 4.3.0.

- The CMakefLists.txt file for release 4.4.3 contains the following
```
#-----------------------------------------------------------------------------
# define package version
#-----------------------------------------------------------------------------
set (API_VERSION_MAJOR 4)
set (API_VERSION_MINOR 4)
set (API_VERSION_PATCH 2)
```
and the resulting napi.h contains
```
#define NEXUS_VERSION   "4.4.2"                /* major.minor.patch */
```
Is this a mistake?

- The README.rst file contains the following:
```
If your library is not in a default location you have basically two options.

1. if the library is installed with a ``pkg-config`` file you can add the path
   to this file to your ``PKG_CONFIG_PATH`` environment variable.
2. define CMake variables during configuration that point to the
   appropriate location.

For the second option the following CMake variables are available

=================  ========================================
CMake variable     Content
=================  ========================================
HDF5_INCLUDE_DIRS  location of HDF5 header files
HDF5_LIBRARY_DIRS  location of HDF5 runtime libraries
HDF4_INCLUDE_DIRS  location of the HDF4 header files
HDF4_LIBRARY_DIRS  location of the HDF4 runtime libraries
MXML_INCLUDE_DIRS  location of the MXML header files
MXML_LIBRARY_DIRS  location of the MXML runtime libraries
=================  =======================================
```
For those of us who are unfamiliar with cmake this is not very helpful.  It would be nice if you would document how to define a CMake variable, i.e. does one edit a file, do it on the command line, etc.  It would also be helpful to document how to invoke CMake to actually build the package.

Thanks,
Mark

**Comment by FreddieAkeroyd** [comment]
With regard to building on Windows I have used:

C:\devel\nexusformat\code\build>"c:\Program Files\CMake\bin\cmake.exe" ..  -G "V
isual Studio 14 2015 Win64" -DHDF5_ROOT="c:/Program Files/HDF_Group/HDF5/1.8.18"
 -DZLIB_LIBRARY="C:\Program Files\HDF_Group\HDF5\1.8.18\lib\zlib.lib" -DENABLE_A
PPS:BOOLEAN=TRUE -DENABLE_CXX:BOOLEAN=TRUE

And then opened the generated NeXus.sln to do the actual building. You can build a package this way using the PACKAGE target of the solution if you have NSIS installer packer on your system. Fot 32bit builds just leave off the "Win64" from the -G option

**Comment by MarkRivers** [comment]
Hi Freddie, thanks for the reply.  My questions were actually about building on Linux, not Windows.

**Comment by zjttoefs** [comment]
Running cmake is now part of the documented build process in README.rst
