### ISSUE TITLE
napi5.c - attr_info function memory leak

### ISSUE THREAD

**Issue by DavidFair** [nexusformat/code#449]
Whilst running valgrind on a programs which uses these libraries on Ubuntu 16.04 I traced a memory leak:

[H5Aiterate2](https://github.com/nexusformat/code/blob/master/src/napi5.c#L2511) passes a function pointer to `attr_info` which calls `strdup`. This returns to the code below

``` c
	if (iname != NULL) {
		if (strcmp(iname, "NX_class") == 0 && pFile->iCurrentG != 0
		    && pFile->iCurrentD == 0) {
			/*
			   skip NXclass attribute which is internal 
			 */
			killAttVID(pFile, vid);
// We returned without calling free here!
			return NX5getnextattra(handle, pName, rank, dim, iType);
		}
		strcpy(pName, iname);
		free(iname);
		iname = NULL;
} else { ...
```
This leaks memory whenever we enter the block skipping NXclass attributes as `iname` is never freed.

**Comment by zjttoefs** [comment]
Many thanks for the report and the fix by the way!
