### ISSUE TITLE
MacOS homebrew install

### ISSUE THREAD

**Issue by MrCrab-2019** [nexusformat/code#468]
I am trying to install the nexus format using homebrew on Mojave. After first installing hdf5 (without problem) I tried:
` brew install brewsci/science/nexusformat --build-from-source`

This then successfully downloads, but then fails about 30% of the way through. The main error appears to be:
`error: incomplete definition of type 'struct _mxml_node_s'`

I'd appreciate any tips!

**Comment by mkoennecke** [comment]
This is an issue with a dependency. Mxml version > 3 break the NAPI compile. This is solved with the test_4.4.4 branch
