### ISSUE TITLE
Conditional including with NXtranslate

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/code#67]
**Original reporter**: _[FreddieAkeroyd](https://github.com/FreddieAkeroyd)_

We are using NXtranslate to convert version 1 muon files into the proposed version 2 files (which are more TOFRAW like in structure). It would be really useful if we could follow a different path through the translation file depending on the value of a variable in the external file i.e. something along the lines of

```
<nxs:condition nxs:location="/path/to/avalue" nxs:test="gt" nxs:value="1">
<something>value if greater than 1</something>
...
</nxs:condition>
<nxs:condition nxs:location="/path/to/avalue" nxs:test="le" nxs:value="1">
<something>value if less than or equal to 1</something>
...
</nxs:condition>
```

to selectively include only parts of the translation file in the output.

**Comment by zjttoefs** [comment]
Reopen if still required.
